Issue F2: Add Announcement Button to Admin Commons List
ucsb-cs156-s24/proj-happycows-s24-4pm-5 pull request #29
Opened 2024-05-17 05:58 UTC by jasontnguyen

## Overview

In this PR, I added a button called 'Announcements' next to the current buttons on the Admin Commons List page. Once clicked, it will lead you to the url `/admin/announcements/{commonsId}` , which will state that it doesn't exist yet as it will be implemented in the next issue.

## Screenshots

![image](https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5/assets/97550852/a2722e2a-25a3-495a-a11e-d19d5dcac329)

## Future Possibilities

- This is the beginning/part of feature F2.
- We can extend this to add the index page for Announcements

## Validation

1. Pull my branch and run on localhost or go to my dev: https://happycows-jasontnguyen-dev.dokku-05.cs.ucsb.edu/
2. Log in as an admin and either create a new common or go to the admin list to click the announcements button
3. Pressing the announcements button should lead you to a 404 but with the correct url in the search bar since the page isn't implemented yet.

## Tests

- [ ] Frontend Unit tests (`npm test`) pass
I created two additional tests that test whether the Announcements button shows up on the admin commons list and if it leads to the right url, which both tests pass.

## Linked Issues

Closes #27

2024-05-17 06:52 UTC, GarvinYoung submitted a review, later dismissed
LGTM

I tested on your dokku link and everything is as described in the pr. The Commons table has an announcement column and when clicking it, the url is correct with the correct commonsID.

2024-05-17 18:48 UTC, pconrad requested changes, later dismissed
So, I like the fact that you are breaking things down into multiple small PRs... that's great!

One thing though, we like to try, always, when merging code into main, to not leave the app in any kind of "broken state", i.e. with buttons that lead to error messages.  So, this one might be "too small".   

At the very least, it would be good to add a temporary page at that URL that says: "feature coming soon" or something like that.

Could we add that before we merge this?

2024-05-17 20:51 UTC, pconrad commented
The details of the failing tests can be found on the website here: 

https://ucsb-cs156-s24.github.io/proj-happycows-s24-4pm-5/

Note that for each PR, there is a column for coverage and stryker which has links to the details reports:

<img width="638" alt="image" src="https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5/assets/1119017/c5bb20f4-324e-427c-8e06-033565673fea">

2024-05-17 22:35 UTC, GarvinYoung approved these changes
LGTM

I checked out the new commits and going to the announcements page for a certain commons no longer returns an error page and returns a placeholder page instead

2024-05-20 19:33 UTC, pconrad approved these changes
LGTM!

2024-05-20 19:34 UTC, merged