Github Commit Info Accessible Through /api/systemInfo API Call
ucsb-cs156-s24/proj-happycows-s24-4pm-5 pull request #37
Opened 2024-05-23 01:14 UTC by GarvinYoung

## Overview
In this pr we allow a user to make an api call to `/api/systemInfo` to get information about the state of the currently deployment. The info it provides is the truth value of the `H2_CONSOLE_ENABLED`, `SHOW_SWAGGER_UI_LINK`, and value of `SOURCE_REPO` env variables defined in the dokku app, `startQtrYYYYQ`, and `endQtrYYYYQ` which are hardcoded, `commitMessage` and `commitId` which is acqruied from a github maven plug, and `githubUrl` which is created from `SOURCE_REPO` and `commitId`.

## Screenshots 
These screenshots are from my dokku app happycows-garvinyoung-dev

As you can see, the response body has the correct `commitID`, `commitMessage`, and truth values for `showSwaggerUILink` and `springH2ConsoleEnabled`
![image](https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5/assets/97640757/ae6bf2cc-6640-4cc1-b1ab-fbb55a502d8e)

## Feedback Request
- I just put the startQtr and endQtr as 20243 and 20244 to represent Spring of 2024, are they supposed to be something else or is this fine?

## Validation
If you want to save time by using my branch which is already set up, skip to step 4 and go to: https://happycows-garvinyoung-dev.dokku-05.cs.ucsb.edu/
1.   type `dokku git:set appname keep-git-dir true` in dokku, replacing `appname` to the correct dokku app
2.   type `dokku config:set apname SOURCE_REPO=https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5` to set the source repo env variable
3.   type `dokku git:sync appname https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5 GY-TrackCommitInfo` to sync your dokku app to this branch
4.   type `dokku ps:rebuild appname` to apply all the previous commands
5.   navigate to the deployed dokku link, you can either access the api call through enabling the swagger link or adding `/api/systemInfo` to the end of the main page url
6. verify that the truth values of the Swagger and H2 Console links are correct as well as the commitMessage and commitId being updated to the lastest commit to this branch

## Tests
In `SystemInfoServiceImplTest.java`, I expanded `test_getSystemInfo()` to cover the additional fields added to the `SystemInfo` class and added `test_githubUrl()` to test that `githubUrl` is correctly created based on `commitId` and `sourceRepo`.

## Linked Issues
Closes #11

2024-05-24 01:03 UTC, nevetsle approved these changes, later dismissed
Tested on dokku, commit message & commitId match the one found on the api/systemInfo

2024-05-24 19:36 UTC, pconrad requested changes, later dismissed
LGTM except for hard coded team name.  

Also I think you can simplify by *only* changing `application.properties`

2024-05-24 19:36 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/services/SystemInfoServiceImpl.java
> +  private String sourceRepo = "https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5";
```suggestion
  private String sourceRepo = "https://github.com/ucsb-cs156/proj-happycows";
```

This needs to stay as the default.  Please override the default by setting SOURCE_REPO in your .env and/or your dokku config:set variables.

Your code has to be, eventually, mergeable into https://github.com/ucsb-cs156/proj-happycows. and this change isn't.

2024-05-24 19:36 UTC, pconrad commented on src/main/resources/application-development.properties
> +app.sourceRepo=${SOURCE_REPO:${$env.SOURCE_REPO:https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5}}
```suggestion
app.sourceRepo=${SOURCE_REPO:${$env.SOURCE_REPO:https://github.com/ucsb-cs156/proj-happycows}}
```

See above.

2024-05-24 19:36 UTC, pconrad commented on src/main/resources/application-integration.properties
> +app.sourceRepo=${SOURCE_REPO:${$env.SOURCE_REPO:https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5}}
```suggestion
app.sourceRepo=${SOURCE_REPO:${$env.SOURCE_REPO:https://github.com/ucsb-cs156/proj-happycows}}
```

See above.

2024-05-24 19:36 UTC, pconrad commented on src/main/resources/application-production.properties
> +app.sourceRepo=${SOURCE_REPO:${$env.SOURCE_REPO:https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5}}
Same here

2024-05-24 19:36 UTC, pconrad commented on src/main/resources/application-wiremock.properties
> +app.sourceRepo=${SOURCE_REPO:${$env.SOURCE_REPO:https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5}}
same here

2024-05-24 19:36 UTC, pconrad commented on src/main/resources/application.properties
> +app.sourceRepo=${SOURCE_REPO:${$env.SOURCE_REPO:https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5}}
same here

2024-05-24 19:36 UTC, pconrad commented on src/main/resources/application.properties
> +app.sourceRepo=${SOURCE_REPO:${$env.SOURCE_REPO:https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5}}
Honestly, putting this one in `application.properties` and leaving it out of the others should be fine.   All of the others "inherit" from `application.properties`.

I suggest that appraoch.

2024-05-24 19:36 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/happiercows/services/SystemInfoServiceImplTests.java
> +    assertEquals("https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5", si.getSourceRepo());
```suggestion
    assertEquals("https://github.com/ucsb-cs156/proj-happycows", si.getSourceRepo());
```

probably, once you make the other changes

2024-05-24 19:36 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/happiercows/services/SystemInfoServiceImplTests.java
> +            "https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5", "abcdef12345"),
here, it's fine, because it's just a test.  Leave the fingerprint of your team here if you like :-)

2024-05-27 04:55 UTC, nevetsle approved these changes
Info is still accessible through the /api/systemInfo API call. LGTM!

2024-06-02 23:39 UTC, pconrad approved these changes
LGTM

2024-06-02 23:39 UTC, pconrad commented on src/main/resources/application-wiremock.properties
>  spring.h2.console.enabled=${H2_CONSOLE_ENABLED:${env.H2_CONSOLE_ENABLED:false}}
Why did you remove the swaggerUILink in the wiremock properties?   I don't think it's a problem, but it doesn't pertain to this PR.

2024-06-02 23:39 UTC, merged