Fixed disallowing users to navigate to unjoined commons
ucsb-cs156-s24/proj-happycows-s24-4pm-5 pull request #51
Opened 2024-05-26 00:09 UTC by nevetsle

## Overview

In this PR, we made changes to PlayPage.js to inform users that trying to navigate to a common they are not apart of, that Access is Denied.
We also made changes to PlayPage.test.js as well as CommonsOverview.test.js to maintain compatibility with the PlayPage.js.

## Screenshots (Optional)

<img width="1057" alt="Screen Shot 2024-05-25 at 4 43 54 PM" src="https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5/assets/124761765/b88064ed-dac0-4a88-9233-9ba96b731143">

## Feedback Request (Optional)
The error messages that indicate userCommons with commonId and userId are still popping up, cluttering up the far right side. If anybody has a way to suppress those with the condition that the user is not apart of the commons, that would be highly needed. Thanks in advance.

## Future Possibilities (Optional)

We could definitely just try redirecting them to a completely different page that says Access Denied instead of showing the Announcements section and Leaderboard button.

## Validation (Optional)

1. Download this branch.
2. On localhost, login, and enter "/play/#" after the URL http://localhost:8080/ where # is the ID of a commons you are not a part of. A message will appear saying Access Denied.

## Tests

- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #9

2024-05-27 08:00 UTC, GarvinYoung approved these changes
LGTM, tested on dokku and "Access Denied" message correctly shows up for commons not joined meanwhile the normal playpage still looks the same

2024-05-29 01:12 UTC, sangitakunapuli requested changes
I think you're on the right track, but you can still navigate to the 'Leaderboard' page for an unjoined commons. In an ideal situation, a user would not be able to see any information about the commons and the toast popups would be silenced.

2024-05-29 22:34 UTC, pconrad approved these changes
LGTM.

We can fix the toasts from the backend on another PR (maybe in F24)

2024-05-29 22:34 UTC, pconrad commented on README.md
> +```
I think this commit belongs in a different PR.

2024-05-29 22:34 UTC, merged